version: "3.7"
services:
  email:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: email
    container_name: email
    ports:
      - 3002:3000
    volumes:
      - ./:/home/email
