version: "3.7"
services:
  email:
    build: 
      context: .
      dockerfile: Dockerfile
    image: email
    container_name: email
    ports:
      - 3002:3000
    environment:
      NODE_ENV: production
      USER: Alerts49876@gmail.com
      PASS: 4?6*GBa@^z7mnUC&5h6
